"""Investigation-journal visual system; analytical calculations live elsewhere.

The paper pages, ink palette, and file tabs replace the generic app shell.
Handwriting is confined to headings; data labels retain a readable sans serif.
"""

JOURNAL_CSS = r'''
__FONT_FACE__
:root{color-scheme:light;--bg:#141612;--panel:#f0e7d0;--panel2:#ddd4ba;--line:#b7ab90;--ink:#292b25;--muted:#5e5b50;--mint:#375544;--amber:#896015;--red:#8d3936;--blue:#375e7e;--gray:#625e57;--dim:#6a6559;--violet:#654976;--hand:"Case Hand","Segoe Print","Bradley Hand",cursive}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;color:var(--ink);background:radial-gradient(ellipse at 50% 0,#3a3c31 0,#1f231d 40%,#101310 100%);font:16px/1.6 "Segoe UI",system-ui,-apple-system,sans-serif}a{color:var(--mint);text-underline-offset:4px}button,a{-webkit-tap-highlight-color:transparent}button{font:inherit;cursor:pointer}button:disabled{opacity:.4;cursor:default}button:focus-visible,a:focus-visible,summary:focus-visible,select:focus-visible{outline:3px solid #985731;outline-offset:4px}h1,h2,h3,p{margin:0}h1,h2,h3{font-family:var(--hand);font-weight:650;line-height:1.12;letter-spacing:0}h1{font-size:clamp(2.5rem,4vw,3.6rem)}h2{font-size:2rem}h3{font-size:1.65rem}strong{font-weight:650}small{font-size:.875rem}.muted{color:var(--muted)}.mono,.value,.number,td{font-variant-numeric:tabular-nums}.eyebrow{font:600 .8rem/1.5 ui-monospace,Consolas,monospace;letter-spacing:.1em;text-transform:uppercase;color:#71614c}.skip{position:absolute;top:-80px;left:12px;z-index:30;background:#f0e7d0;padding:12px;color:#222}.skip:focus{top:12px}
/* A file header and horizontal journal tabs replace the software sidebar. */
.sidebar{max-width:1370px;margin:0 auto;padding:27px 30px 0;color:#ece8da;display:grid;grid-template-columns:1fr auto;align-items:center;column-gap:24px}.brand{display:block;color:#eeeade;text-decoration:none;width:fit-content}.brand-mark,.nav-label{display:none}.brand strong{font-family:var(--hand);font-size:clamp(2rem,3.5vw,3rem);line-height:1;letter-spacing:.025em;font-weight:650;text-shadow:1px 2px 3px #000}.brand small{display:block;font:.8rem/1.6 ui-monospace,Consolas,monospace;letter-spacing:.17em;text-transform:uppercase;color:#b9bbaa;margin-top:8px}.side-bottom{grid-column:2;grid-row:1;text-align:right}.side-bottom p{max-width:280px;font-size:.875rem;color:#c4c6b9;margin-top:8px}.side-bottom a{display:inline-block;font-size:.875rem;color:#dcdccc;margin:5px 0 0 18px}.side-bottom .badge{color:#c7d2b7;border-color:#899078}.badge{display:inline-block;padding:3px 8px;border:1px solid #77654c;color:#6b442d;font:600 .75rem/1.5 ui-monospace,Consolas,monospace;letter-spacing:.055em;text-transform:uppercase;border-radius:1px}.nav{grid-column:1/-1;display:flex;gap:7px;padding-top:26px;padding-left:21px}.nav a{display:flex;align-items:center;gap:11px;min-height:50px;padding:8px 26px 10px;background:#b6b299;border:1px solid #898974;border-bottom:0;border-radius:5px 8px 0 0;color:#393d32;text-decoration:none;font:600 1.6rem/1.1 var(--hand);box-shadow:0 -2px 9px #0002}.nav a span{font:500 .75rem ui-monospace,Consolas,monospace;color:#65644e}.nav a:hover{background:#d5cdb2}.nav a[aria-current=page]{background:#e9dfc5;color:#342f26;position:relative;z-index:2;border-color:#c0b295;box-shadow:0 -3px 10px #0003}.nav a[aria-current=page]:after{content:"";position:absolute;left:25px;right:25px;bottom:8px;border-bottom:2px solid #843b31;transform:rotate(-1deg)}
/* The entire working surface reads as one journal, with ruled dividers. */
main{max-width:1310px;margin:0 auto 35px;padding:22px 39px 27px 50px;position:relative;background:linear-gradient(90deg,#b8ab8e 0,#e0d4b8 12px,#f0e7d0 27px,#ebe1c7 100%);border:1px solid #aa9b7c;border-radius:2px 5px 5px 2px;box-shadow:0 0 0 6px #3d3c2f,0 0 0 8px #171a15,0 16px 45px #0008}.topbar{display:flex;justify-content:space-between;gap:18px;align-items:center;border-bottom:1px solid var(--line);padding:0 0 13px;margin-bottom:25px;color:#6c6353;font:.8rem/1.5 ui-monospace,Consolas,monospace;letter-spacing:.015em}.topbar span:last-child{text-align:right}.mast{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;margin-bottom:23px}.mast .eyebrow{margin-bottom:8px}.mast p{color:var(--muted);max-width:820px;margin-top:10px;line-height:1.6}.scope-chip{white-space:nowrap;color:#764138;border:2px solid #945449;padding:5px 10px;transform:rotate(-3deg);font:600 .8rem/1.5 ui-monospace,monospace;text-transform:uppercase}.view[hidden]{display:none}.view{animation:enter .18s ease-out}@keyframes enter{from{opacity:.6;transform:translateY(3px)}to{opacity:1;transform:none}}
.stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:0;margin:24px 0 28px;border-top:2px solid #8c826c;border-bottom:2px solid #8c826c;background:#e5dbc140}.stat{padding:14px 20px 16px;border-right:1px solid var(--line);min-width:0}.stat:last-child{border-right:0}.stat .label{font-size:.875rem;color:var(--muted)}.stat .value{font:650 clamp(2.3rem,3.7vw,3.4rem)/1.15 var(--hand);letter-spacing:0;margin:6px 0;color:#33392c}.stat.highlight .value{color:#2f543d}.stat .detail{font-size:.8rem;color:var(--muted);line-height:1.5}.grid{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(0,1fr);gap:30px;margin-bottom:25px}.grid.equal{grid-template-columns:repeat(2,minmax(0,1fr))}.panel{min-width:0;padding:22px 0 20px;border-top:1px solid #a79c82;background:transparent}.grid>.panel+.panel{padding-left:28px;border-left:1px solid #b9ad9166}.panel.full{margin-bottom:22px}.panel-head{display:flex;align-items:start;justify-content:space-between;gap:18px;margin-bottom:22px}.panel-head p{font-size:.875rem;color:var(--muted);margin-top:6px}.panel-num{font:.75rem/1.5 ui-monospace,monospace;letter-spacing:.06em;color:var(--dim);white-space:nowrap;padding-top:8px}.note{font-size:.875rem;color:var(--muted);margin-top:20px;line-height:1.65}.insight{border-left:3px solid #526951;padding:12px 15px;background:#c9d1b44f;margin-top:22px;font-size:.9rem}.insight strong{color:#34523c}.insight.warm{background:#d6bf7b35;border-color:#8c6b2e}.insight.warm strong{color:#79511e}.scope-note{display:flex;gap:15px;padding:17px 0;border-top:1px dashed #95876e;border-bottom:1px dashed #95876e;font-size:.875rem;color:var(--muted)}.scope-note strong{color:#673f2e;white-space:nowrap}.footer{display:flex;justify-content:space-between;gap:14px;margin-top:26px;padding-top:14px;border-top:1px solid var(--line);font-size:.8rem;color:var(--dim);flex-wrap:wrap}.footer a{color:var(--muted)}
.legend{display:flex;gap:11px 18px;flex-wrap:wrap;margin-top:20px;font-size:.875rem;color:var(--muted)}.legend span{display:flex;align-items:center;gap:7px}.swatch{width:10px;height:10px;display:inline-block;flex:none;background:var(--c);border:1px solid #0001}.stack-item{margin-top:23px}.stack-label{display:flex;justify-content:space-between;gap:12px;margin-bottom:9px;font-size:.9rem}.stack-label small{color:var(--muted)}.stack{display:flex;height:45px;background:#d2c8ae;border:1px solid #786f5e;overflow:hidden}.stack .segment{height:100%;display:flex;align-items:center;justify-content:center;background:var(--c);color:#fffaf0;font-size:.875rem;font-weight:650;min-width:0;border-right:1px solid #eee5ca66}.segment:last-child{border-right:0}.segment:hover{filter:brightness(1.12)}.axis{display:flex;justify-content:space-between;color:var(--dim);font:.75rem ui-monospace,monospace;margin:8px 0 0}.relation-row{margin:18px 0}.bar-label{display:flex;align-items:baseline;justify-content:space-between;gap:12px;margin-bottom:7px;font-size:.9rem}.bar-label strong{white-space:nowrap}.bar-label small{font-weight:400;color:var(--muted);margin-left:7px}.track{background:#d9cfb6;height:9px;overflow:hidden}.fill{height:100%;background:var(--c)}.bar-foot{font-size:.75rem;color:var(--dim);margin-top:5px}.definition{display:grid;grid-template-columns:10px 1fr;gap:12px;margin-top:18px}.definition .swatch{margin-top:9px}.definition p{font-size:.875rem;color:var(--muted);margin-top:3px}.definition strong{font-size:.95rem}
.segmented{display:flex;flex-wrap:wrap;gap:3px;border:1px solid #ad9d7f;padding:3px;background:#dfd2b5;width:fit-content}.segmented button{background:none;border:0;padding:7px 10px;font-size:.875rem;color:#575141}.segmented button[aria-pressed=true]{background:#444c3d;color:#fff5db}.segmented button:hover{outline:1px solid #7a785e}.chart-scroll{overflow-x:auto}.heatmap{width:100%;border-collapse:separate;border-spacing:5px;table-layout:fixed}.heatmap th{font-weight:400;color:var(--muted);font-size:.875rem;padding:6px;text-align:center;overflow-wrap:anywhere}.heatmap th:first-child{text-align:left;width:24%}.heatmap td{text-align:center;border:1px solid #9b9b7c;padding:16px 8px;background:var(--shade);font-size:1.4rem;font-weight:600;color:#212b22}.heatmap small{display:block;font-size:.75rem;font-weight:400;color:#363e30}.heatmap-wrap{min-width:480px}.plot{width:100%;height:auto;display:block;min-width:560px}.plot text{font-family:"Segoe UI",system-ui,sans-serif;fill:var(--muted);font-size:14px}.plot .model-label{fill:var(--ink);font-size:15px}.plot .score{fill:var(--ink);font-weight:650}.plot .gridline{stroke:#aa9f87;stroke-dasharray:3 4}.plot .ci{stroke:var(--c);stroke-width:3}.plot circle{fill:var(--c);stroke:#eee4cb;stroke-width:3}.plot .selected-label{fill:#31533d}
details{margin-top:20px;border-top:1px dotted #a4967a;padding-top:13px}summary{cursor:pointer;color:#5e563f;font-size:.875rem}summary:hover{color:#75382d}.table-scroll{overflow-x:auto;margin-top:14px}.data-table{width:100%;border-collapse:collapse;font-size:.875rem;white-space:nowrap}.data-table th{text-align:left;font-size:.8rem;color:#59503e;font-weight:600;padding:10px 12px;background:#d8ceb3}.data-table td{padding:10px 12px;border-bottom:1px solid #baad90}.selected-row td{color:var(--mint)}.blank{padding:24px;color:var(--muted);border:1px dashed var(--line)}.steps{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.step{padding:15px;border:1px solid var(--line);background:#e3d8bc55}.step .number{font:650 2.5rem/1.2 var(--hand);color:var(--mint);margin:8px 0}.step p{font-size:.875rem;color:var(--muted)}.step .eyebrow{color:var(--dim)}.metric-inline{display:flex;gap:25px;flex-wrap:wrap;margin-top:20px}.metric-inline strong{display:block;font:650 2.25rem/1.2 var(--hand);color:var(--mint)}.metric-inline small{color:var(--muted)}
.error-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}.error-card{background:#f5eddb;border:1px solid #beb094;padding:24px;box-shadow:2px 4px 0 #b2a18345;min-width:0}.error-top{display:flex;justify-content:space-between;gap:14px;color:var(--muted);font:.8rem/1.5 ui-monospace,monospace;padding-bottom:12px;border-bottom:1px solid #b6a988}.error-card blockquote{margin:18px 0;padding:0;white-space:pre-wrap;overflow-wrap:anywhere;font:400 1rem/1.8 Georgia,serif;max-height:250px;overflow-y:auto}.labels{display:flex;gap:18px;flex-wrap:wrap;border-top:1px solid #b6a988;padding-top:15px;font-size:.8rem}.labels strong{display:block;font-size:.875rem;margin-top:4px}.pill{font-size:.75rem;border:1px solid #9b7665;padding:2px 6px;color:#754833}.pager{display:flex;justify-content:space-between;align-items:center;margin:22px 0;gap:15px;color:var(--muted);font-size:.875rem}.pager button{background:#dacfaf;color:#3e3e30;border:1px solid #a3997c;padding:8px 14px;margin-left:6px}.evidence-tools{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:22px;flex-wrap:wrap}.evidence-tools label{color:var(--muted);font-size:.875rem}.evidence-tools select{font:inherit;font-size:.875rem;padding:8px;background:#eee5ce;color:var(--ink);border:1px solid #a3997c;margin-left:8px}
@media(min-width:1500px){main{margin-bottom:50px}}@media(max-width:1100px){.sidebar{padding-left:25px;padding-right:25px}main{margin-left:22px;margin-right:22px;padding:24px 28px 24px 35px}.grid{grid-template-columns:1fr}.grid>.panel+.panel{padding-left:0;border-left:0}.grid.equal{grid-template-columns:repeat(2,minmax(0,1fr))}.grid.equal>.panel+.panel{padding-left:20px;border-left:1px solid #b9ad9166}.mast .scope-chip{display:none}.stat{padding:13px}.nav a{padding-left:20px;padding-right:20px}}@media(max-width:760px){.sidebar{display:block;padding:20px 14px 0}.brand strong{font-size:2.6rem}.brand small{font-size:.75rem}.side-bottom{display:none}.nav{gap:4px;padding:20px 0 0}.nav a{flex:1;justify-content:center;text-align:center;padding:9px 6px 14px;font-size:1.25rem;min-height:56px}.nav a span{display:none}.nav a[aria-current=page]:after{left:8px;right:8px;bottom:8px}main{margin:0 10px 25px;padding:19px 16px 22px 21px;box-shadow:0 0 0 4px #3d3c2f,0 12px 25px #0006}.topbar{font-size:.75rem;gap:12px;align-items:start;margin-bottom:23px}.mast{margin-bottom:20px}h1{font-size:2.7rem}h2{font-size:1.8rem}.mast p{font-size:1rem}.stats{grid-template-columns:repeat(2,minmax(0,1fr));margin-top:20px}.stat:nth-child(2){border-right:0}.stat:nth-child(-n+2){border-bottom:1px solid var(--line)}.stat .value{font-size:2.6rem}.stat .detail{font-size:.8rem}.grid,.grid.equal{grid-template-columns:1fr;gap:10px}.grid.equal>.panel+.panel{padding-left:0;border-left:0}.panel{padding-top:20px}.panel-head{flex-wrap:wrap}.error-grid{grid-template-columns:1fr}.scope-note{display:block}.scope-note strong{display:block;margin-bottom:5px}.stack{height:42px}.stack .segment{font-size:.75rem}.stack-label{flex-wrap:wrap}.bar-label small{display:block;margin-left:0}.steps{grid-template-columns:repeat(2,1fr);gap:10px}.step{padding:12px}.heatmap td{padding:12px 5px}.footer{font-size:.75rem}.error-card{padding:18px}}
/* Motion follows the journal interaction: cover hinge, then an ink stroke. */
.nav a[aria-current=page]:after{transform-origin:left center;animation:draw-underline .38s .06s cubic-bezier(.35,.1,.4,1) both}
@keyframes draw-underline{from{transform:rotate(-1deg) scaleX(0)}to{transform:rotate(-1deg) scaleX(1)}}
.view{animation:none}#journal-shell[hidden],#book-intro[hidden]{display:none}
body[data-book-state=closed],body[data-book-state=opening]{overflow:hidden}
.book-intro{position:fixed;inset:0;z-index:50;background:radial-gradient(ellipse at 50% 35%,#3b3e32 0,#1c211c 48%,#0a100f 100%);overflow:hidden;min-height:100dvh}
.book-trigger{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:28px;width:100%;height:100%;min-height:100dvh;border:0;background:transparent;color:#e8dec3;padding:30px 20px;cursor:pointer;perspective:1600px}
.book-trigger:disabled{opacity:1;cursor:default}.book-trigger:focus-visible{outline:0}.book-trigger:focus-visible .closed-book{outline:3px solid #d6bd7e;outline-offset:10px}
.closed-book{position:relative;display:block;width:min(410px,76vw);height:min(530px,65dvh);min-height:280px;flex-shrink:0;perspective:1400px;transform:rotate(-2deg);filter:drop-shadow(12px 18px 18px #0008)}
.book-leaves{position:absolute;inset:5px -7px -5px 7px;border:1px solid #837a60;border-radius:3px 9px 9px 3px;background:repeating-linear-gradient(0deg,#d6c9a7 0px,#d6c9a7 2px,#9e9375 3px,#e0d3b3 4px);box-shadow:3px 3px 0 #3e3a2d}
.book-cover{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:flex-start;padding:45px 30px 28px 40px;border:1px solid #8c7c5b;border-left:12px solid #39352c;border-radius:3px 9px 9px 3px;background:linear-gradient(90deg,#514735 0,#302f27 14px,#57513e 20px,#464737 48%,#373d30 100%);box-shadow:inset 0 0 0 5px #25291e,inset 0 0 0 6px #777457,inset 0 0 35px #1118;transform-origin:left center;backface-visibility:hidden;transform-style:preserve-3d;text-align:center}
.cover-kicker{font:500 .75rem/1.6 ui-monospace,Consolas,monospace;letter-spacing:.08em;color:#b9b391}.cover-title{font:650 clamp(2.2rem,6vw,3.3rem)/1.1 var(--hand);color:#e8dec3;margin-top:28px;letter-spacing:.01em}.cover-subtitle{font:600 clamp(1.8rem,4vw,2.5rem)/1.1 var(--hand);margin-top:24px;color:#c4c2a1}.cover-rule{display:block;width:70px;border-bottom:1px solid #999373;margin:25px auto 17px}.cover-caption{font:400 .8rem/1.7 ui-monospace,Consolas,monospace;max-width:230px;color:#c0bba0}.cover-author{margin-top:auto;padding-top:20px;font:600 1.35rem/1.4 var(--hand);color:#d3c9ad}.cover-author small{font:400 .75rem ui-monospace,Consolas,monospace;color:#aba58d}.open-prompt{display:block;font:500 1.45rem/1.3 var(--hand);text-align:center;color:#ddd4b9}.open-prompt span{display:block;margin-top:8px;font:400 .75rem/1.5 ui-monospace,Consolas,monospace;color:#a2a78f}
body[data-book-state=opening] .book-cover{animation:open-cover .86s .24s cubic-bezier(.45,.05,.2,1) both}
body[data-book-state=opening] .book-intro{background:transparent;pointer-events:none}
body[data-book-state=opening] .closed-book{animation:release-book 1.1s ease both}
body[data-book-state=opening] .book-leaves{animation:fade-leaves .55s .5s ease both}
body[data-book-state=opening] .open-prompt{opacity:0;transition:opacity .15s}
body[data-book-state=opening] #journal-shell{animation:reveal-journal 1.1s ease both}
@keyframes open-cover{0%{transform:rotateY(0deg)}100%{transform:rotateY(-165deg)}}
@keyframes release-book{0%{opacity:1;transform:rotate(-2deg) scale(1)}22%{opacity:1;transform:rotate(0deg) scale(1)}65%{opacity:1;transform:rotate(0deg) scale(1.05)}100%{opacity:0;transform:rotate(0deg) scale(1.1)}}
@keyframes fade-leaves{from{opacity:1}to{opacity:0}}
@keyframes reveal-journal{0%,30%{opacity:0;transform:scale(.96)}100%{opacity:1;transform:scale(1)}}
@media(max-height:650px){.book-trigger{gap:17px;padding:18px}.closed-book{height:70dvh;min-height:220px;width:min(350px,68vw)}.book-cover{padding:22px 24px 20px 30px}.cover-title{margin-top:15px;font-size:2.4rem}.cover-subtitle{margin-top:12px;font-size:1.8rem}.cover-rule{margin:12px auto}.cover-caption{display:none}.cover-author{padding-top:10px}.open-prompt{font-size:1.2rem}.open-prompt span{margin-top:3px}}
@media(max-height:450px){.closed-book{min-height:180px}.book-cover{padding:15px 20px}.cover-kicker,.cover-rule,.cover-caption,.open-prompt span{display:none}.cover-title{font-size:2rem;margin-top:8px}.cover-subtitle{font-size:1.5rem;margin-top:8px}.cover-author{font-size:1rem;padding-top:8px}}
@media(prefers-reduced-motion:reduce){.nav a[aria-current=page]:after{animation:none;transform:rotate(-1deg) scaleX(1)}body[data-book-state=opening] .book-cover,body[data-book-state=opening] .closed-book,body[data-book-state=opening] .book-leaves,body[data-book-state=opening] #journal-shell{animation:none}.open-prompt{transition:none}}
@media print{#book-intro{display:none!important}#journal-shell[hidden]{display:block}body[data-book-state=closed],body[data-book-state=opening]{overflow:visible}}
@media(max-width:480px){.nav{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));padding-bottom:10px}.nav a{border:1px solid #898974;border-radius:2px;min-height:46px}.topbar{flex-direction:column;gap:5px}.topbar span:last-child{text-align:left}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.view{animation:none}}@media print{body{background:white;color:black}.sidebar,.segmented,.pager,.evidence-tools{display:none}main{margin:0;padding:0;max-width:none;background:white;border:0;box-shadow:none}.view[hidden]{display:block}.view{break-before:page}.panel,.stat,.error-card{break-inside:avoid}.error-card{box-shadow:none}.error-card blockquote{max-height:none;overflow:visible}.muted,.note,.panel-head p,.mast p,.stat .label,.stat .detail,.topbar,.footer{color:#333}.plot text{fill:#333}.heatmap td{color:black}.scope-note{background:white;color:black}}
'''
