"""Build ordered research notebooks backed by the tested package.

The notebooks explain and orchestrate the workflow. Reusable analytical logic
remains in ``src/phasma_review`` so notebook execution does not create a second
implementation or depend on hidden state.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK_DIR = ROOT / "notebooks"


def markdown(source: str) -> dict[str, object]:
    normalized = source.strip()
    return {
        "cell_type": "markdown",
        "id": hashlib.sha1(f"markdown:{normalized}".encode()).hexdigest()[:8],
        "metadata": {},
        "source": [line + "\n" for line in normalized.splitlines()],
    }


def code(source: str) -> dict[str, object]:
    normalized = source.strip()
    return {
        "cell_type": "code",
        "id": hashlib.sha1(f"code:{normalized}".encode()).hexdigest()[:8],
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [line + "\n" for line in normalized.splitlines()],
    }


NOTEBOOKS: dict[str, list[dict[str, object]]] = {
    "00_annotation_protocol.ipynb": [
        markdown(
            """
# 00: Blinded annotation protocol

## Annotation design

Annotator A codes all 262 reviews from text alone. Annotator B independently
codes 80 reviews, including every row assigned to the locked evaluation
partition. Recommendation, playtime, heuristic flags, and prior labels remain
hidden during annotation.
"""
        ),
        code(
            """
from phasma_review.annotations import annotation_status
from phasma_review.paths import ANNOTATOR_A_PATH, ANNOTATOR_B_PATH

annotation_status(), ANNOTATOR_A_PATH, ANNOTATOR_A_PATH.with_suffix('.xlsx'), ANNOTATOR_B_PATH, ANNOTATOR_B_PATH.with_suffix('.xlsx')
"""
        ),
        markdown(
            """
Complete both files using `docs/ANNOTATION_GUIDE.md`. Do not load the raw
source in an annotator's session because it contains the hidden Steam signal.
"""
        ),
    ],
    "01_annotation_quality.ipynb": [
        markdown(
            """
# 01: Annotation quality and adjudication

## Reliability and adjudication

Agreement is measured between two independent human annotators. Every semantic
disagreement and inconsistent duplicate-text label enters an adjudication
queue, and downstream analysis remains blocked until final decisions exist.
"""
        ),
        code(
            """
from phasma_review.annotations import annotation_status, build_adjudication_queue

status = annotation_status()
status
"""
        ),
        code(
            """
# Run only when both status entries report valid_and_complete=True.
if all(status[name].get("valid_and_complete", False) for name in ("annotator_a", "annotator_b")):
    adjudication_queue = build_adjudication_queue()
    display(adjudication_queue.head())
else:
    print("BLOCKED: finish both independent annotation files first.")
"""
        ),
    ],
    "02_full_corpus_analysis.ipynb": [
        markdown(
            """
# 02: Full-corpus measurement

## Measurement design

Descriptive results use all 262 adjudicated rows in the observed corpus. Hard
contradictions, mixed opinions, non-evaluative text, and insufficient text
remain separate. Every estimate includes a denominator and uncertainty
interval.
"""
        ),
        code(
            """
from phasma_review.analysis import run_analysis
from phasma_review.schema import AnnotationIncompleteError

try:
    analysis = run_analysis()
    display(analysis["prevalence"])
except AnnotationIncompleteError as error:
    print(f"BLOCKED: {error}")
"""
        ),
    ],
    "03_behavior_and_robustness.ipynb": [
        markdown(
            """
# 03: Behavior and robustness

## Robustness design

Missing playtime remains missing. Medians receive bootstrap intervals, sparse
association tables are flagged, and conclusions are checked against duplicate
handling, low-confidence labels, and alternate playtime cut points. These are
associations, not causal effects.
"""
        ),
        code(
            """
from phasma_review.paths import ASSOCIATION_RESULTS_PATH, BEHAVIOR_RESULTS_PATH, SENSITIVITY_RESULTS_PATH
import pandas as pd

for path in (BEHAVIOR_RESULTS_PATH, ASSOCIATION_RESULTS_PATH, SENSITIVITY_RESULTS_PATH):
    if path.exists():
        print(path.name)
        display(pd.read_csv(path).head(20))
    else:
        print(f"BLOCKED: {path.name} is generated by notebook 02 after label finalization.")
"""
        ),
    ],
    "04_model_validation.ipynb": [
        markdown(
            """
# 04: Model validation

## Evaluation design

Candidate selection occurs only in repeated stratified group cross-validation
on development data. Most-frequent and Steam-mapping baselines are explicit.
The one-standard-error rule controls complexity, and the locked test is used
only after selection with group-bootstrap intervals.
"""
        ),
        code(
            """
from phasma_review.modeling import run_modeling
from phasma_review.schema import AnnotationIncompleteError

try:
    model_result = run_modeling()
    display(model_result["selection_summary"])
    display(model_result["test_results"])
except (AnnotationIncompleteError, ValueError) as error:
    print(f"BLOCKED: {error}")
"""
        ),
    ],
    "05_dashboard_and_handoff.ipynb": [
        markdown(
            """
# 05: Audited dashboard and handoff

## Reporting design

Missing booleans display as `Unknown`, categories retain their exact
definitions, model uncertainty is visible, and diagnostic error examples use
a documented deterministic selection rule.
"""
        ),
        code(
            """
from phasma_review.dashboard import DASHBOARD_HTML_PATH, run_dashboard
from phasma_review.schema import AnnotationIncompleteError

try:
    tables = run_dashboard()
    print(f"Dashboard: {DASHBOARD_HTML_PATH}")
    {name: frame.shape for name, frame in tables.items()}
except AnnotationIncompleteError as error:
    print(f"BLOCKED: {error}")
"""
        ),
        markdown(
            """
The resulting model remains research-only. Temporal validation requires at
least 100 genuinely later, independently labeled eligible reviews; use the
contract in `data/external/` rather than extrapolating from this window.
"""
        ),
    ],
}


def main() -> None:
    NOTEBOOK_DIR.mkdir(parents=True, exist_ok=True)
    metadata = {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {"name": "python", "version": "3.12"},
    }
    for name, cells in NOTEBOOKS.items():
        payload = {
            "cells": cells,
            "metadata": metadata,
            "nbformat": 4,
            "nbformat_minor": 5,
        }
        (NOTEBOOK_DIR / name).write_text(
            json.dumps(payload, indent=1, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        print(f"wrote {NOTEBOOK_DIR / name}")


if __name__ == "__main__":
    main()
